import type { MenuCategory } from "@/types/menu";

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "hair-removal",
    name: "光脱毛",
    nameEn: "Hair Removal",
    description:
      "痛みが少ない光脱毛を採用。高額な契約不要の都度払いで、自分のペースで通えます。3箇所同時で10%OFF〜9箇所で25%OFFのセット割引あり。",
    icon: "zap",
    items: [
      {
        id: "removal-a",
        name: "Aパーツ",
        parts: ["おでこ", "ほほ", "鼻下", "あご", "眉間", "指（手）"],
        price: 4400,
        unit: "1回",
      },
      {
        id: "removal-b",
        name: "Bパーツ",
        parts: ["うなじ", "肩", "ワキ", "もみあげ", "耳", "デコルテ"],
        price: 5500,
        unit: "1回",
      },
      {
        id: "removal-c",
        name: "Cパーツ",
        parts: ["胸", "ひじ上", "ひじ下", "腹部", "指（足）"],
        price: 6600,
        unit: "1回",
      },
      {
        id: "removal-d",
        name: "Dパーツ",
        parts: ["背中", "おしり"],
        price: 7700,
        unit: "1回",
      },
      {
        id: "removal-e",
        name: "Eパーツ",
        parts: ["ひざ上", "ひざ下"],
        price: 8800,
        unit: "1回",
      },
      {
        id: "removal-v",
        name: "Vパーツ",
        parts: ["Vゾーン"],
        price: 11000,
        unit: "1回",
      },
      {
        id: "removal-i",
        name: "Iパーツ",
        parts: ["Iゾーン"],
        price: 11000,
        unit: "1回",
      },
      {
        id: "removal-o",
        name: "Oパーツ",
        parts: ["Oゾーン"],
        price: 11000,
        unit: "1回",
      },
      {
        id: "removal-vio",
        name: "V.I.O SET",
        parts: ["V・I・O 3箇所セット"],
        price: 29700,
        unit: "1回",
        popular: true,
        note: "デリケートゾーンも男性スタッフが丁寧に対応",
      },
      {
        id: "removal-all",
        name: "ALL全身脱毛（V.I.O含む）",
        parts: ["全身全パーツ＋V.I.O"],
        price: 52470,
        originalPrice: 122430,
        unit: "1回",
        badge: "30%OFF",
      },
      {
        id: "shaving",
        name: "シェービング追加",
        parts: ["施術部位のシェービング"],
        price: 1500,
        unit: "1回",
      },
    ],
    newClientDiscount: [
      { session: 1, discountRate: 80 },
      { session: 2, discountRate: 60 },
      { session: 3, discountRate: 40 },
    ],
  },
  {
    id: "hbl",
    name: "ハリウッドブロウリフト・Wax",
    nameEn: "Hollywood Brow Lift & Wax",
    description:
      "眉毛のリフトアップ・形成と眉Wax脱毛のメニュー。自然な眉の形を長期キープ。",
    icon: "sparkles",
    items: [
      {
        id: "hbl-wax",
        name: "ハリウッドブロウリフト＆Wax",
        parts: ["眉毛のリフトアップ＋Wax脱毛"],
        price: 4950,
        originalPrice: 7000,
        unit: "1回",
        popular: true,
      },
      {
        id: "hbl-standard",
        name: "眉Waxまたはハリウッドブロウリフトのみ",
        parts: ["眉Wax単体またはHBL単体"],
        price: 2950,
        originalPrice: 4000,
        unit: "1回",
      },
      {
        id: "nose-wax",
        name: "鼻毛ワックス",
        parts: ["鼻毛のWax脱毛"],
        price: 550,
        unit: "1回",
      },
    ],
  },
  {
    id: "whitening",
    name: "セルフホワイトニング",
    nameEn: "Self Whitening",
    description:
      "サロンで手軽に白い歯へ。通いやすい料金設定。",
    icon: "smile",
    items: [
      {
        id: "whitening-1",
        name: "セルフホワイトニング",
        parts: ["20分照射"],
        price: 5500,
        unit: "1回",
        popular: true,
      },
    ],
  },
  {
    id: "skincare",
    name: "フォトフェイシャル・スキンケア",
    nameEn: "Photo Facial & Skin Care",
    description:
      "光・水流技術を使ったスキンケアメニュー。肌のキメを整え、透明感ある肌へ。",
    icon: "activity",
    items: [
      {
        id: "photo-facial",
        name: "フォトフェイシャル",
        parts: ["顔全体への光照射"],
        price: 11000,
        unit: "1回",
        popular: true,
        badge: "県内初",
      },
      {
        id: "water-peeling",
        name: "ウォーターピーリング",
        parts: ["水流での角質ケア"],
        price: 2200,
        unit: "1回",
      },
    ],
  },
  {
    id: "dep",
    name: "DEP・痩身",
    nameEn: "DEP & Body Slimming",
    description:
      "福島県メンズサロン初導入のDEP（ダーマエレクトロポレーション）と、キャビテーション＆ラジオ波による痩身メニュー。導入価格で提供中。",
    icon: "zap",
    items: [
      {
        id: "dep-treatment",
        name: "DEP（ダーマエレクトロポレーション）",
        parts: ["顔全体への有効成分導入"],
        price: 16000,
        originalPrice: 18000,
        unit: "1回",
        popular: true,
        badge: "県内初",
      },
      {
        id: "cavitation-abdomen",
        name: "キャビテーション＆ラジオ波（腹部・背中）",
        parts: ["腹部または背中"],
        price: 7000,
        originalPrice: 8000,
        unit: "1回",
      },
      {
        id: "cavitation-legs",
        name: "キャビテーション＆ラジオ波（両脚）",
        parts: ["両脚"],
        price: 5000,
        originalPrice: 6000,
        unit: "1回",
      },
      {
        id: "cavitation-arms",
        name: "キャビテーション＆ラジオ波（両腕）",
        parts: ["両腕"],
        price: 3000,
        originalPrice: 4000,
        unit: "1回",
      },
    ],
  },
];
